Fix LoRA saving format to be diffusers-compatible
Changed from saving entire transformer with save_pretrained() to using
save_lora_weights() which saves only the LoRA adapters in the correct format.

Previous (incorrect):
  unwrapped_model = accelerator.unwrap_model(pipe.transformer)
  unwrapped_model.save_pretrained(save_path)

Now (correct):
  unwrapped_transformer = accelerator.unwrap_model(pipe.transformer)
  pipe.transformer = unwrapped_transformer
  pipe.save_lora_weights(save_path, safe_serialization=True)

This fixes the KeyError when loading LoRA with pipe.load_lora_weights():
  KeyError: 'base_model.model.double_blocks.0.img_mod.lin.lora_A.weight'

The saved LoRA will now be compatible with:
  pipe.load_lora_weights("path/to/lora")